[package]
name = "snake"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35"
rand = "0.8"

[profile.release]
strip = "symbols"
lto = true
codegen-units = 1
panic = "abort"